tasks:
  - name: Installing Ciao
    before: |
      sudo apt-get update && \
      sudo apt-get install -y \
          curl \
          rlwrap \
          emacs-nox && \
      sudo apt-get clean && \
      curl https://ciao-lang.org/boot -sSfL | sh -s -- --prebuilt-bin local-install

vscode:
  extensions:
    - ciao-lang.ciao-prolog-vsc
