tasks:
  - name: Installing Tools
    before: |
      sudo apt-get update && \
      sudo apt-get install sudo curl git xdg-utils build-essential rlwrap -y && \
      sudo apt-get clean
    command: curl https://ciao-lang.org/boot -sSfL | sh -s -- --prebuilt-bin local-install
# TODO: Upload extension to OpenVSX
# vscode:
#   extensions:
#     - ciao-lang.ciao-prolog-vsc
