tasks:
  - name: Installing Tools
    before: |
      sudo apt-get update && \
      sudo apt-get install -y \
          curl \
          texlive \
          texinfo \
          imagemagick \
          rlwrap \
          emacs-nox && \
      sudo apt-get clean
    command: |
      curl https://ciao-lang.org/boot -sSfL | sh -s -- get devenv

vscode:
  extensions:
    - ciao-lang.ciao-prolog-vsc
